### ISSUE TITLE
nix-shell fails with "error: attribute 'version' missing"

### ISSUE THREAD

**Issue by apalmer27516** [holochain/holonix-archive#11]
I had version 21 running on this machine as of July 3rd. Work on this might already be in progress per a comment in  #9 

> Ubuntu 18.04.2 LTS; Intel® Core™ i3-4000M CPU @ 2.40GHz × 4; 64Bit
> Linux kernel: Linux version 4.15.0-52-generic (buildd@lgw01-amd64-051) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019
> 1) Successfully ran install to bring up "nix-shell --pure"
> 2) "hc --version" shows "hc 0.0.21-alpha1"...

Now I get:

`nix-shell --pure --show-trace https://holochain.love
error: while evaluating the attribute 'buildInputs' of the derivation 'holonix-shell' at /nix/store/nqi6201vd2zbaz8qlvsz7xp5bzxxgr1k-holochain.love/nix-shell/default.nix:18:2:
while evaluating the attribute 'text' of the derivation 'hn-release-branch' at /nix/store/5m8hfg0zcxl5rv25yqlap6cjbhf3y0mv-nixpkgs-channels-8634c3b/pkgs/build-support/trivial-builders.nix:7:14:
while evaluating the attribute 'release.branch' at /nix/store/nqi6201vd2zbaz8qlvsz7xp5bzxxgr1k-holochain.love/release/default.nix:10:4:
while evaluating the attribute 'release.version.current' at /nix/store/nqi6201vd2zbaz8qlvsz7xp5bzxxgr1k-holochain.love/default.nix:9:3:
attribute 'version' missing, at /nix/store/nqi6201vd2zbaz8qlvsz7xp5bzxxgr1k-holochain.love/release/default.nix:10:24
`

**Comment by spiralcrew-ou** [comment]
Can confirm this and 'nix-shell https://holochain.love' shows above msg.

**Comment by feamcor** [comment]
+1

**Comment by fbeauregard** [comment]
+1

**Comment by dhtnetwork** [comment]
Hi all: the dev core team is aware of the issue and working on a fix from a documentation perspective. Standby...

**Comment by tommycp3** [comment]
![2019-07-11_15-33-42](https://user-images.githubusercontent.com/13199826/61024546-50d39480-a3f1-11e9-8b8f-bc104005297c.png)
+1 Thanks yeah I got the same issue.

**Comment by marcusnewton** [comment]
Temporary fix, you can download a previous release (0.0.3) and it should work

**Comment by dhtnetwork** [comment]
Hi everyone: this issue has been resolved/fixed with the release of 0.0.23-alpha1.  

The bug in Holonix that was breaking holochain.love has been fixed.

**Comment by dhtnetwork** [comment]
Please confirm if this has resolved the issue. Once confirmed we can close the issue. Thank you

**Comment by fbeauregard** [comment]
Resolved confirmed here. Thanks.

**Comment by apalmer27516** [comment]
Yes, tested and it is resolved. Closing it.
