### ISSUE TITLE
out of date docs re: love branch and blessing

### ISSUE THREAD

**Issue by thedavidmeister** [holochain/holonix-archive#117]
> interesting comment about docs and when they should be updated. Re: "https://docs.holochain.love/docs/configure/ says that https://holochain.love is a convenience url that points to the master branch of the holonix repo on github. Seems like that documentation is out of date."  Post Should the page be updated to reflect the blessing process now?  Latest version not hitting the love branch yet.  etc etc. 

from @dhtnetwork

**Comment by pospi** [comment]
FWIW holochain.love has caused a lot of confusion with my development team. It would be good if it was more clearly indicated in the developer docs that this points to the *latest* version of Holochain and is great for getting started, but probably not what you want once developing a serious project.

Basically I have to include "**DO NOT USE https://holochain.love WITH THIS REPO!!**" in my README because otherwise people will, and they'll get all sorts of potential breakages that are hard to debug as a result.

**Comment by dhtnetwork** [comment]
Thanks pospi for the feedback and comment. Yes, I think the more clear we can be better. This could be a huge time saver for all involved.

**Comment by thedavidmeister** [comment]
@pospi ok yes, i totally agree that pinning is the best approach, the reason `.love` exists is because there was a lot of pull to produce "a one liner" installation, but obviously that isn't compatible with ongoing versioning/pinning/teamwork for any serious project

it's more for hackathons and throwaway experiments than something you'd try to take to production

the pros and cons of both are documented at https://docs.holochain.love/docs/configure/ but i'm open to hearing about how we can make it clearer when to use each

**Comment by pospi** [comment]
It might be more the quickstart that is throwing people, hard to say. Getting people to read docs is an everlasting battle :P

I think maybe anywhere that holochain.love is mentioned, there could be a small caveat that "once you start developing, people usually move to a pinned configuration [link to config docs]", sorta thing?

**Comment by thedavidmeister** [comment]
@pospi yeah, its _really_ hard to know what to do, our approach so far has been doing changes, then finding ~5 people "off the street" to try and install holochain from the guide, record if/where they get stuck and then iterate

there's a natural tension between "information overload" in the onboarding and "production ready" level of infrastructure

@dhtnetwork and i are definitely appreciating and tracking your suggestions and are planning to do a docs sweep once the current backlog simmers down a bit :+1:

**Comment by dhtnetwork** [comment]
> there's a natural tension between "information overload" in the onboarding and "production ready" level of infrastructure

Yes this is spot on terms of striking a good balance.
