### ISSUE TITLE
Optimise to avoid having to redownload Holochain crates when executing `cargo test` from inside shell

### ISSUE THREAD

**Issue by pospi** [holochain/holonix-archive#14]
Having to download this archive twice is a real pain point for those on slow or spotty internet connections.

**Comment by thedavidmeister** [comment]
@pospi when do you see this redownloading? not sure how to reproduce the issue here

**Comment by pospi** [comment]
- boot a new `nix-shell` from holochain.love
- run `cargo test`
- cargo now pulls packages from Github, but `holochain-rust` & all dependencies have already been downloaded via Nix, no?

![image](https://user-images.githubusercontent.com/437540/62818233-36bfda00-bb88-11e9-9a70-fe8edbc6c9c0.png)

The same also happens when initing VSCode from within `nix-shell` as the Rust extension runs `rls` and this kicks off the same download process.

If it's only downloading once then I'm fine with it, but eager not to thrash this limited internet connection unnecessarily.

**Comment by thedavidmeister** [comment]
@pospi ohhh no, that's not quite what is happening here

nix is currently downloading some precompiled holochain rust binaries and putting them on the path

to test you need to compile whatever is local and test that, which currently uses cargo under the hood

we _do_ try pretty hard to set cargo incremental building up and have it "just work", so if you see it redownloading and recompiling a lot after the first test run, then that is not right

there might be more sophisticated nix/rust integrations coming from @yegortimoshenko in the future based on parsing `Cargo.lock` and using nix to cache _that_ but that's a very different setup

**Comment by pospi** [comment]
Ah cool, gotcha... this (bin / src) makes sense then. Just making sure it's as optimised as is reasonable (:
