### ISSUE TITLE
Include commands necessary for completing tutorials

### ISSUE THREAD

**Issue by pdaoust** [holochain/holonix-archive#142]
There's a [conversation on the docs repo](https://github.com/holochain/docs-pages/issues/176) that suggests that Holonix should include everything necessary to complete the tutorials. I can see their point -- I was thinking of Holonix as "everything necessary for an app dev to get started", but that includes being able to learn Holochain, which strongly suggests supporting the tutorials as a first-class consumer.

Currently this means including only one package:

* curl

I'll update this issue if I find any more packages.

**Comment by mmahut** [comment]
@pdaoust do you have any other packages in mind?

**Comment by mmahut** [comment]
`curl` has been added as part of https://github.com/holochain/holonix/blob/master/CHANGELOG.md#added-5

**Comment by pdaoust** [comment]
@mmahut sorry, I missed this request; Gmail was filtering my GitHub notifications away from sight. `curl` was the only pressing need for the sake of the tutorials; thank you!

**Comment by mmahut** [comment]
Awesome!
