### ISSUE TITLE
Your current version of Yarn is out of date. The latest version is "1.22.4", while you're on "1.17.3".

### ISSUE THREAD

**Issue by philipbeadle** [holochain/holonix-archive#155]

**Comment by mmahut** [comment]
To solve this, we need to first update `holo-nixpkgs` (https://github.com/Holo-Host/holo-nixpkgs/pull/453) and then point holonix to use it instead of `nixpkgs`.

**Comment by steveej** [comment]
We've got yarn "1.22.5" as of de6cbd9ab0a1a5129e6be56037b0993881c4c895
