### ISSUE TITLE
Hello Holo hc package fails  (failed to resolve: could not find 'document_(join & Select)_macro` in `futures_util)

### ISSUE THREAD

**Issue by ghost** [holochain/holonix-archive#159]
Holochain Forum

    hc-package-cargo-error

Environment

    Lenovo P52
    NixOS 5.4.42
    nix-shell (Nix) 2.3.4
    hc 0.0.47-alpha1

Steps

Creation of a Holochain project, using the typical "Hello World" sequence of steps:

    hc init <project-name>
    cd <project-name>
    hc generate zomes/<zome-name> rust-proc
    hc package

Errors

    failed to resolve: could not find `document_join_macro` in `futures_util
    failed to resolve: could not find `document_select_macro` in `futures_util`

Output

[nix-shell:~/holochain/coreconcepts/cc_tuts]$ hc generate zomes/hello rust-proc
downloading and extracting tarball from: https://github.com/holochain/rust-proc-zome-template/archive/master.tar.gz
> zomes/hello/
> zomes/hello/
> zomes/hello/code
> zomes/hello/code/.hcbuild
> zomes/hello/code/Cargo.toml
> zomes/hello/code/src
> zomes/hello/code/src/lib.rs
> zomes/hello/zome.json

[nix-shell:~/holochain/coreconcepts/cc_tuts]$ hc package
> CARGO_TARGET_DIR=${CARGO_TARGET_DIR:-/tmp/my_first_app/target} && echo $CARGO_TARGET_DIR 
"CARGO_TARGET_DIR=${CARGO_TARGET_DIR:-/tmp/my_first_app/target} && echo $CARGO_TARGET_DIR "
/home/jack/target
> CARGO_TARGET_DIR=${CARGO_TARGET_DIR:-/tmp/my_first_app/target} && cargo build --release --target=wasm32-unknown-unknown --target-dir=$CARGO_TARGET_DIR
"CARGO_TARGET_DIR=${CARGO_TARGET_DIR:-/tmp/my_first_app/target} && cargo build --release --target=wasm32-unknown-unknown --target-dir=$CARGO_TARGET_DIR"
    Updating crates.io index
   Compiling futures v0.3.2
error[E0433]: failed to resolve: could not find `document_join_macro` in `futures_util`
   --> /home/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.3.2/src/lib.rs:561:15
    |
561 | futures_util::document_join_macro! {
    |               ^^^^^^^^^^^^^^^^^^^ could not find `document_join_macro` in `futures_util`

error[E0433]: failed to resolve: could not find `document_select_macro` in `futures_util`
   --> /home/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.3.2/src/lib.rs:584:15
    |
584 | futures_util::document_select_macro! {
    |               ^^^^^^^^^^^^^^^^^^^^^ could not find `document_select_macro` in `futures_util`

error[E0433]: failed to resolve: could not find `document_join_macro` in `futures_util`
   --> /home/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.3.2/src/lib.rs:561:15
    |
561 | futures_util::document_join_macro! {
    |               ^^^^^^^^^^^^^^^^^^^ could not find `document_join_macro` in `futures_util`

error[E0433]: failed to resolve: could not find `document_select_macro` in `futures_util`
   --> /home/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.3.2/src/lib.rs:584:15
    |
584 | futures_util::document_select_macro! {
    |               ^^^^^^^^^^^^^^^^^^^^^ could not find `document_select_macro` in `futures_util`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0433`.
error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0433`.
error: could not compile `futures`.
warning: build failed, waiting for other jobs to finish...
error: could not compile `futures`.

To learn more, run the command again with --verbose.
Error: Couldn't traverse DNA in directory "/home/jack/holochain/coreconcepts/cc_tuts": command CARGO_TARGET_DIR=${CARGO_TARGET_DIR:-/tmp/my_first_app/target} && cargo build --release --target=wasm32-unknown-unknown --target-dir=$CARGO_TARGET_DIR was not successful

[Hello_Holo_Error.txt](https://github.com/holochain/holonix/files/4680724/Hello_Holo_Error.txt)

**Comment by 0hack0dev7** [comment]
I have the same problem.
But there is a workaround.

delete in the home/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.3.2/src/lib.rs following functions:
--> 'document_select_macro' 
--> 'document_join_macro'
and recompile

After that it worked

**Comment by ghost** [comment]
This workaround fixes the problem
Thanks @0hack0dev7 
Closing issue
