### ISSUE TITLE
prechecks on hn-release-cut

### ISSUE THREAD

**Issue by neonphog** [holochain/holonix-archive#16]
Make sure we have needed info before even starting, specifically:

- github release oath token
- crates.io api key

can do something like:

```
if [ -f ${CARGO_HOME:-$HOME/.cargo}/credentials ]; then
  echo 'yay'
else
  echo 'boo' && exit 1
fi
```

**Comment by thedavidmeister** [comment]
yup @neonphog , similar complaint from @struktured

**Comment by thedavidmeister** [comment]
also probably want to check the commit hash matches `git rev-parse HEAD` too

**Comment by thedavidmeister** [comment]
also probably want to steal the config audit from core
