### ISSUE TITLE
hc test fails 0.0.24-alpha2

### ISSUE THREAD

**Issue by nphias** [holochain/holonix-archive#18]
i get this error after following the install instructions on a mac osx 10.14:

[nix-shell:/nix/my_app]$ hc test
Packaging files for testing to file: "/nix/my_app/dist/my_app.dna.json"
> cargo build --release --target=wasm32-unknown-unknown --target-dir=/Users/thomas/nix-holochain/main_zome/target
    Updating git repository `https://github.com/holochain/holochain-rust`
error: failed to load source for a dependency on `hdk`

Caused by:
  Unable to update https://github.com/holochain/holochain-rust?tag=v0.0.24-alpha2

Caused by:
  failed to find tag `v0.0.24-alpha2`

Caused by:
  reference 'refs/tags/v0.0.24-alpha2' not found; class=Reference (4); code=NotFound (-3)
Error: command cargo build --release --target=wasm32-unknown-unknown --target-dir=/Users/thomas/nix-holochain/main_zome/target was not successful

why does it have to fetch and try and update github?.. when it should be a local test?

**Comment by AlxndrPsclt** [comment]
+1 Affect me too.

**Comment by ghost** [comment]
> why does it have to fetch and try and update github?.. when it should be a local test?

the fetching from github is done by nix-shell, not hc test. Nix-shell lazy loads its dependencies. So only when you run hc test, which I assume compiles your code, it will see that there is a dependency missing.
Nix will then try to get it. This will fail because at the moment the tag is not there. 
The missing tag is probably just a human error by someone.

By the way: I have the same error and I'm learning about nix to override this dependency (not quite there yet)

**Comment by nphias** [comment]
yes its a typo ... to fix this edit your Cargo.toml file (my_app/zomes/my_zome/code/Cargo.toml)
for entries hdk and holochain_wasm_utils ... change the tag from v0.0.24-alpha2 to 0.0.24-alpha2  (remove the v).   and then it works ... i like things that work out the box.. please devs update this for the noobs and close the issue :)  dont make me do a fork.. pull-request..!  :)

**Comment by thedavidmeister** [comment]
ah yes! sorry!

this is the result of some of the crates using `vx.x.x` and some using `x.x.x` tags

now everything uses the latter

i didn't even realise all the places the `v` was being used so i obviously missed some :(

is there anything that should be changed in the code, or is this something that will impact existing `*.dna.json` only?

@nphias  @pragmaticmind @AlxndrPsclt

**Comment by ghost** [comment]
@thedavidmeister 
I made the changes @nphias suggested

> to fix this edit your Cargo.toml file (my_app/zomes/my_zome/code/Cargo.toml)

Running **hc test** compiled the zome.

The test failed, but this was related to some missing nodejs module @holochain/diorama, but I'm speculating that the cause lies with my Windows | Vagrant setup and has something to do with symlinks.

**Comment by thedavidmeister** [comment]
that could be the case on windows/vagrant if there are binaries that would normally be symlinked in

there is a workaround i hacked together on a similar repo for `karma` test running:

https://github.com/thedavidmeister/nix-shadow-cljs/blob/master/karma/default.nix#L6

might be worth looking into :thinking:

**Comment by ghost** [comment]
@thedavidmeister  symlinks are indeed the reason why the Vagrant scenario from https://developer.holochain.org/start.html doesn't work.

If I'm correct, it will not work for any Windows|Virtualbox|Vagrant user.

The most robust solution I found was, adding the following to your [Vagrantfile](https://gist.githubusercontent.com/thedavidmeister/8e92696538fe04cf6b44552e14d29195/raw/4dcb83b983e8dcd2f5db213b0cde5a533af556a6/Vagrantfile):
```
# Add the ability to make simlink in shared windows drive. You have to start vagrant from an powershell with administrator rights.
vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/holochain-vagrant", "1"]
```
The only downside is that you need to run _vagrant up_ as administrator.
Would consider adding this to your Vagrantfile?

I can make a suggestion for updating the docs.

**Comment by thedavidmeister** [comment]
@pragmaticmind i saw this option and decided against it because it requires running things as administrator

from my experience at hackathons and general usage, this kind of things seems beyond many people

it's pretty easy to just wrap the binaries in a nix script that essentially behaves as a symlink anyway :)

**Comment by thedavidmeister** [comment]
this is old now
