### ISSUE TITLE
Why not publish a package on nixpkgs? Or a flake?

### ISSUE THREAD

**Issue by happysalada** [holochain/holonix-archive#215]
I arrived here from trying to find out what the install steps where doing.
It's a little unintuitive to me that I can't see the source of what I am installing when I follow the installation steps.
How about publishing a package on nixpkgs?
It looks to me that you have somebody with commit rights to nixpkgs in your core team. So getting timely updates would not be a problem.
How about publishing a flake? That could be another alternative, people could choose to update their dependencies anytime.
Just a thinking out loud here.
Thanks for providing great software!

**Comment by happysalada** [comment]
Just to argument my point a little more
Currently, providing the installation in a nix-shell has the following drawback
- If the nix gc is not running (for users not familiar with nix and how to configure it), it will increase consumption on the drive. I don't think this is what you want.
- If the nix gc is running, then the developpers needs to re-download the whole package suit everytime he wants a shell. On my machine (2015 macOS) this takes 1h16m33s. Also, the gc can actually run against a running nix-shell. Resulting in the following
```
[nix-shell:~/Projects]$ holochain --version
bash: /nix/store/kbq3v72nj9jznllyhzzd2rckjg41j1g1-holochain/bin/holochain: No such file or directory
```
- It's hard to know what the installation script is really doing, it requires trust on the developper's side. 
- Having a package publicly available would make it easier for people to push updates and fixes.

**Comment by steveej** [comment]
Thank you for your feedback @happysalada 

> I arrived here from trying to find out what the install steps where doing.

Let me tell you that you're about halfway there :smile:



>  It's a little unintuitive to me that I can't see the source of what I am installing when I follow the installation steps.

I'm not sure what you mean by "source" and I'm slightly confused. This repository contains the shell definitions that are sourced by `nix-shell` when you point it towards this repository (possibly via a redirection URL as instructed in the Holochain setup guide). Please let me know which part is not clear so I can try to point you at the things you're interested in.



>  How about publishing a package on nixpkgs?

Indeed we haven't come that far, but we do [maintain a package in an overlay over at holo-nixpkgs](https://github.com/Holo-Host/holo-nixpkgs/blob/29f51c212a1f0ee976704cc99a6e398d44537c58/overlays/holo-nixpkgs/default.nix#L138-L171). IMHO, two things are currently holding back maintaining these derivations in the community's nixpkgs: We're still working out our release schedule and test suite, and the packaging experience isn't great, see [this stalled PR where I try to improve it](https://github.com/NixOS/nixpkgs/pull/105825).



>  How about publishing a flake? That could be another alternative, people could choose to update their dependencies anytime.

Please explain how a flake could help to improve the situation as my theoretical understanding seems to be lacking. I'm happy to experiment with that if there's a prospect of solving an issue.

On the GC issues. I'm aware of this caveat and I also feel the need to improve it. I wrote [this bash-based wrapper binary named holonix](https://github.com/holochain/holonix/blob/f8bf0836b83ec6515e9da66a29302f18d298bbfa/pkgs/holonix.nix#L88) which uses nix's `--add-root` in combination with `--indirect` to prevent the GC from removing the most-recent shell derivation. Unfortunately the script has been surfacing issues on various non-NixOS distributions and macOS, so we stopped advocating for it.

[This line in the unreleased changelog](https://github.com/holochain/holonix/blob/3baaa5f0f52d7bf0a9273c0b1570f9ec2b46d45b/CHANGELOG-UNRELEASED.md#added) shows how to use the script if you're curious.

**Comment by happysalada** [comment]
Thanks for taking the time to answer!

Let me explain what I meant by can't see the source.
The [install instructions](https://developer.holochain.org/docs/install/) mention the following step
`nix-shell https://nightly.holochain.love`
Two problems here. Because it is a shell I don't see what steps are being taken by nix. I don't know what derivations are being pulled or what is being installed at all. Usually when you install something, the terminal gives you info about what is happening.
Second problem. I do not know what holochain.love is linked to. I came to this repo after looking around, but there is no way for me to be sure that this is really what is being pulled from holochain.love.
I'll trust you. However just remember from an outside perspective, it's not very transparent.

Thanks a lot for the overlay link, this is exactly what I was looking for in the advanced install steps (unfortunately those contain the same as the simple steps). Those expressions pack a punch!
Regarding the stalled PR, it seems that there could be a way to do what you wanted by overriding the buildPhase. I don't know exactly what you were trying to build.

How would publishing a flake improve the situation.
You can define a flake in your own repo. People can choose to use that as a dependency. You can decide to change your flake anytime and people can choose to update it to any specific commit they want. Publishing a package to nixpkgs can be time-consuming and you can't publish updates as often as you would want. However with a flake, you can update anytime you want. That overlay you linked to would be a good candidate for a flake. I do admit though that flakes are still in experimental stage, and so you would be requiring people to go off the blessed track for now. The earliest estimates as to when flakes will be published I've heard is the end of the year. I'm just suggesting that alternative in case you don't have the time/energy of publishing to nixpkgs.

I'm going to take another look at this and will try to be more constructive with a solution.

**Comment by mhuesch** [comment]
hi! glad to see this issue. I would be very interested in using flakes to integrate holonix/holochain into my / @sacredcapital's code.

my impression is that adding a `flake.nix` file would not be too difficult, and could reuse the existing nix infrastructure in such a way that future updates to the repo would not require modifications of `flake.nix`. if that is the case then it seems like doing the work once would be worth it.

I can take a look at writing a `flake.nix` file.

**Comment by happysalada** [comment]
if you want to pin specific versions of the dependencies, it will require some modifications of the input.
For example, you have input that specify a url, and that url will contain a version (likely to make sure everything is working together). That version will likely be updated on every release.
If all the dependencies are tracking master, then you don't need to update the flake.nix

**Comment by steveej** [comment]
this was implemented in https://github.com/holochain/holochain/pull/1863. 

documentation is being updated in all places, and you can find minimal working examples at https://github.com/holochain/holochain/blob/develop/holonix/README.md.

please create an issue over at the holochain repo with the _nix_ label if you encounter any issues or have questions. i'm looking forward receiving any feedback :slightly_smiling_face:
