### ISSUE TITLE
M1 Mac Issues installing holonix

### ISSUE THREAD

**Issue by feznyng** [holochain/holonix-archive#224]
Hi, I'm currently attempting to install the holonix shell according to the quick start guide on an M1 mac running Big Sur. I've successfully installed nixOS but I'm getting an error related to the Rust development tools installation when installing Holonix. 
```
 nix-shell https://nightly.holochain.love
error: Component resolution failed for rust-default-1.54.0
- note: available extensions are cargo, clippy, clippy-preview, llvm-tools-preview, miri, miri-preview, reproducible-artifacts, rls, rls-preview, rust-analysis, rust-analyzer-preview, rust-docs, rust-mingw, rust-src, rust-std, rustc, rustc-dev, rustc-docs, rustfmt, rustfmt-preview
- Host component `rust-docs` doesn't support target `aarch64-apple-darwin`
```

Is there an alternative installation method I can use? Thank you!

**Comment by kaichaosun** [comment]
I still encounter this issue, need to bump rust to latest I guess.
Can we reopen this issue?

**Comment by kaichaosun** [comment]
Can someone reopen this issue?
