### ISSUE TITLE
holonix as a base layer for HoloPortOS

### ISSUE THREAD

**Issue by thedavidmeister** [holochain/holonix-archive#30]
this would improve the consistency and avoid reinventing wheels between dev environments (holonix) and holo "prod" environments HPOS

things to do

- [ ] have HPOS reference holonix
- [ ] ensure same pinnings in currently shared deps
- [ ] merge useful stuff from HPOS into holonix
- [ ] dedupe holonix work from HPOS

**Comment by lukateras** [comment]
Would like to do the first three and advise on fourth.

**Comment by thedavidmeister** [comment]
@yegortimoshenko yeah that makes sense, i even think that this would be spread across a few PRs

**Comment by thedavidmeister** [comment]
@yegortimoshenko hey could we capture that conversation we had the other day about the overlay approach?

it was really interesting and probably the way to go

**Comment by steveej** [comment]
Work on this has been started, although it's the opposite. We use packages defined in holo-nixpkgs in holonix.
