### ISSUE TITLE
Qt Dependency

### ISSUE THREAD

**Issue by freesig** [holochain/holonix-archive#36]
Hey Just wondering what the Qt dependency is for?
It takes over 1.5 hours to build on my machine and I wonder if it could be optional?
I'm using a pretty modest Mac however I think there will be other users in a similar boat.
I will time it on a faster machine tonight and report back here.
I'm new here so apologies if this is not the correct place to ask this question.

**Comment by thedavidmeister** [comment]
@freesig it is used by the c bindings in `holochain-rust`

at some point android development was being prototyped

i could see Qt support moving into a separate repo and then the dependency here would sit as an extension to holonix there

i also see this being very slow

**Comment by freesig** [comment]
I'm a bit lost with how to move qt to holochain-rust.
What I think is going on is: 
1. holonix is pulling in and building the package `pkgs.qt59.qmake` 
2. The [this qmake](https://github.com/holochain/holochain-rust/blob/9ded890152703e0fe7ca065a1d015348bb36859f/c_binding_tests/hc_dna/qmake.pro) file links to the a rust library `holochain_dna_c_binding`, 
3. Links `QT += testlib` which I assume is the QT testing library
4. Links `QT -= gui` which I assume takes out the gui part of QT?

So is what you're proposing is to add to the holochain-rust/qt/default.nix so that it grabs the package like holonix does now?
Am I on the right track?

**Comment by thedavidmeister** [comment]
@freesig move the whole `qt` folder out of here and into `holochain-rust`
