### ISSUE TITLE
Aggressive code size optimization options should be WASM only

### ISSUE THREAD

**Issue by neonphog** [holochain/holonix-archive#5]
- `optimization-level = "z"` - https://github.com/holochain/holonix/blob/master/rust/config.nix#L58

This value affects the inline threshold per https://rust-embedded.github.io/book/unsorted/speed-vs-size.html#optimize-for-size often generating smaller binary code (though sometimes it actually increases it!) at the cost of generating code that often runs much slower.

For WASM, when we have constraints about the size of code we can load, this makes sense, but for system binaries, where the disk space taken by our binary is completely insignificant when compared to our CPU usage, I think we want to stick with the default of opt-level `0` for debug code and `2` for release code (i.e. we should not specify in the environment variable).

**Comment by thedavidmeister** [comment]
@neonphog this makes perfect sense and is related to https://github.com/holochain/holonix/pull/20
