### ISSUE TITLE
use makeWrapper for hc so that it has a version of cargo to work with

### ISSUE THREAD

**Issue by thedavidmeister** [holochain/holonix-archive#55]
this is something that @yegortimoshenko and i talked about a bit

basically when installing `hc` with `nix-env` it works fine.. until you hit a command that uses `cargo` internally

of course, `cargo` doesn't exist outside the `nix-shell`

even worse, the users sees instructions telling them to install `rustup`!!

https://forum.holochain.org/t/my-first-app-hc-generate-zomes-my-zome-rust-not-installed/718

```
[vagrant@nixos:/vagrant/my_first_app]$ hc generate zomes/my_zome
This command requires the cargo command, which is part of the Rust toolchain.
Generating a Rust based Zome depends on having Rust installed.
As a first step, get Rust installed by using rustup https://rustup.rs/.
Holochain requires you use the nightly-2019-07-14 toolchain.
With Rust already installed switch to it by running the following commands:
$ rustup toolchain install nightly-2019-07-14
$ rustup default nightly-2019-07-14
```

so the solution for this setup would be to use the `makeWrapper` offered by nix which makes a micro shell for individual binaries, so we could "inject" `cargo` into `hc` apparently

sounds like black magic to me, but apparently it works :man_shrugging:

**Comment by dellams** [comment]
Ok great, how do I use makeWrapper then? Thanks :)

**Comment by thedavidmeister** [comment]
@dellams if you point to any version of holonix `v0.0.31`+ it will be in there, you don't have to do anything extra
