### ISSUE TITLE
Improve the release process

### ISSUE THREAD

**Issue by pegaltier** [holochain/holonix-archive#56]
holochain v0.0.29-alpha2 has been released so I wanted to try but holonix is still working with holochain 28… On the other side the developer page is mentioning 0.0.29-alpha2 but if a developer install holo he will get the 28. 

Improvement:
1 new version of holonix must be delivered after each new version of holochain.

Source:
https://developer.holochain.org/start.html

**Comment by thedavidmeister** [comment]
@pegaltier this is part of the process documented at https://hackmd.io/x33-yfZSTECDrtxlIEMUag and https://hackmd.io/-pQHRPQ8TcKQ-PjFnJWYMw

not sure who cut `v0.0.29-alpha2` but i suppose they didn't push it to holonix :man_shrugging: 

@zippy any idea?

**Comment by thedavidmeister** [comment]
pretty sure this was just a mistake, i've bumped to `v0.0.29-alpha2` in the latest holonix release
