### ISSUE TITLE
error when hc packaging since rust bump: Could not compile `futures-core-preview`

### ISSUE THREAD

**Issue by marcusnewton** [holochain/holonix-archive#9]
Please close if unrelated, but this issue started occurring since NixOS autoupdated around 6 hours ago

Referencing issue [#1576](https://github.com/holochain/holochain-rust/issues/1576) in core repo

**Comment by neonphog** [comment]
I'm seeing this as well: https://github.com/holochain/lib3h/pull/125#issuecomment-508534156

**Comment by thedavidmeister** [comment]
@marcusnewton ah sorry!

changing/normalising some release processes and it hasn't fully propagated yet

working on fixing/documenting all the disruptions

**Comment by marcusnewton** [comment]
Issue still occurring:

```console
Compiling futures-core-preview v0.3.0-alpha.12
error[E0432]: unresolved import `core::task::LocalWaker`
 --> /home/vagrant/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-preview-0.3.0-alpha.12/src/future/future_obj.rs:6:12
  |
6 |     task::{LocalWaker, Poll},
  |            ^^^^^^^^^^ no `LocalWaker` in `task`

error[E0432]: unresolved imports `core::task::LocalWaker`, `core::task::UnsafeWake`
 --> /home/vagrant/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-preview-0.3.0-alpha.12/src/task/mod.rs:8:35
  |
8 | pub use core::task::{Poll, Waker, LocalWaker, UnsafeWake};
  |                                   ^^^^^^^^^^  ^^^^^^^^^^
no `UnsafeWake` in `task`
  |                                   |
  |                                   no `LocalWaker` in `task`

error[E0432]: unresolved imports `std::task::Wake`, `std::task::local_waker`, `std::task::local_waker_from_nonlocal`
  --> /home/vagrant/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-preview-0.3.0-alpha.12/src/task/mod.rs:10:21
   |
10 | pub use std::task::{Wake, local_waker, local_waker_from_nonlocal};
   |                     ^^^^  ^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^^^^^^^ no `local_waker_from_nonlocal` in `task`
   |                     |     |
   |                     |     no `local_waker` in `task`
   |                     no `Wake` in `task`
   |                     help: a similar name exists in the module: `Waker`

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0432`.
error: Could not compile `futures-core-preview`.
warning: build failed, waiting for other jobs to finish...
error: build failed
Error: command cargo build --release --target=wasm32-unknown-unknown --target-dir=/home/vagrant/nix-holochain/example/target was not successful

[nix-shell:/vagrant/example]$ hc --version
hc 0.0.23-alpha1
```

**Comment by zo-el** [comment]
I'm seeing this as well: https://github.com/Holo-Host/DeepKey/pull/21

**Comment by pospi** [comment]
Same for me on latest `master` (`e37e00d`) as well as latest tagged version.

What's the syntax to run the 'flush' command? (see https://github.com/holochain/holonix/issues/13)

**Comment by pospi** [comment]
Still erroring out on `0.0.20` @ `e2f8101`. Unsure whether it's still a bug though, or if there is some internal build state left over from previously.

**Comment by zo-el** [comment]
@pospi, I would recommend updating your hc to v0.0.24-alpha2. It should solve this issue

**Comment by pospi** [comment]
Any chance we can get this package updated to use the latest then? Nix has sort of been a blocker for us since we tried to switch over a bit over a week ago.

**Comment by pospi** [comment]
Update: it seems like I can't do this. I updated the version pegged in `config.nix` and it fails before it even gets started in attempting to download the `cli` package from Github, which hasn't been released yet.

**Comment by thedavidmeister** [comment]
@pospi @zo-el @marcusnewton the futures API changed in the rust compiler itself, `LocalWaker` does not exist

`0.0.24-alpha2` has all the core fixes needed for this

if you're using anything that changed in rust you'll need to update it
