### ISSUE TITLE
flesh out CI docs

### ISSUE THREAD

**Issue by thedavidmeister** [holochain/holonix-archive#94]
https://docs.holochain.love/docs/ci/

**Comment by milkyklim** [comment]
Hey David, 

I am interested in CI part docs. I've managed to set up CI with Github Actions/Workflows (see [into-pieces](https://github.com/milkyklim/into-pieces/blob/master/.github/workflows/main.yml)) but I am lost trying to _cache_ holonix, holochain.love and project (cargo) files. 

Any chance you can provide minimal example (github, circle or travis) to show how it works?

**Comment by thedavidmeister** [comment]
@milkyklim i haven't been caching because my experience with that approach is that it is very inconsistent across different CI providers and often doesn't provide much additional speed vs. simply creating a docker box that has everything you need already in it, as the cache is hosted on AWS somewhere and _downloaded_ in roughly the same way a docker would be

for an example on how to have a docker box ready to go for CI checkout the main holochain-rust repo :D

**Comment by milkyklim** [comment]
Extensive answer, thanks!
