### ISSUE TITLE
ssh permissions issues (ship/pin ssh)

### ISSUE THREAD

**Issue by thedavidmeister** [holochain/holonix-archive#96]
@pospi

https://forum.holochain.org/t/what-is-the-worst-of-holonix-onboarding-2019-q3/547/5?u=thedavidmeister

> The other issue with Nix is encountering Bad owner or permissions on $HOME/.ssh/config when attempting to run any commands that interact with SSH (i.e. git). Unsure if there is a way to fix this (if so, docs would be great @thedavidmeister); but that’s the other context switch contributors still need to be aware of.

> Ok turns out this was a me thing, I had that file set to 0664 instead of 0644. Weird that nothing else has ever complained about it, though. Might be one to add in the list of gotchas.

...

> Git differs by a patch version, so… maybe. ssh doesn’t seem to have a CLI switch to print out the version :woman_shrugging:

**Comment by thedavidmeister** [comment]
maybe related? https://github.com/holochain/holonix/issues/7

**Comment by pospi** [comment]
I think that's a different thing, probably not something that needs to be logged. Github must have tightened their allowable signature schemes- @bhaugen was getting a similar error when attempting to clone over SSH recently, and he only generated those keys late 2018 :/
